# Generated by Django 6.0.4 on 2026-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_card_deck_deckcard_delete_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='img_src',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, through='myapp.DeckCard', to='myapp.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
