# Generated by Django 6.0.4 on 2026-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_metadata_card_img_src_deck_cards_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='last_updated',
            field=models.CharField(max_length=100),
        ),
    ]
