# Generated by Django 6.0.4 on 2026-05-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_metadata_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
        migrations.AddField(
            model_name='deck',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
