class Card():
    """A class representing the resources generated by a MTG card.
    Cares about how much mana and card draw the card generates.
    """

    def __init__(self, turn):
        pass

    def get_mana(self, turn):
        return 0
    
    def get_draw(self, turn):
        return 0